package models;
// Generated 07-feb-2017 13:33:47 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion implements java.io.Serializable {

	private Integer idTransaccion;
	private Cliente clienteByIdClienteVendedor;
	private Cliente clienteByIdClienteComprador;
	private Producto producto;
	private Date fechaTransaccion;

	public Transaccion() {
	}

	public Transaccion(Cliente clienteByIdClienteVendedor, Cliente clienteByIdClienteComprador, Producto producto,
			Date fechaTransaccion) {
		this.clienteByIdClienteVendedor = clienteByIdClienteVendedor;
		this.clienteByIdClienteComprador = clienteByIdClienteComprador;
		this.producto = producto;
		this.fechaTransaccion = fechaTransaccion;
	}

	public Integer getIdTransaccion() {
		return this.idTransaccion;
	}

	public void setIdTransaccion(Integer idTransaccion) {
		this.idTransaccion = idTransaccion;
	}

	public Cliente getClienteByIdClienteVendedor() {
		return this.clienteByIdClienteVendedor;
	}

	public void setClienteByIdClienteVendedor(Cliente clienteByIdClienteVendedor) {
		this.clienteByIdClienteVendedor = clienteByIdClienteVendedor;
	}

	public Cliente getClienteByIdClienteComprador() {
		return this.clienteByIdClienteComprador;
	}

	public void setClienteByIdClienteComprador(Cliente clienteByIdClienteComprador) {
		this.clienteByIdClienteComprador = clienteByIdClienteComprador;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Date getFechaTransaccion() {
		return this.fechaTransaccion;
	}

	public void setFechaTransaccion(Date fechaTransaccion) {
		this.fechaTransaccion = fechaTransaccion;
	}

}
